ALTER TABLE Souls ALTER COLUMN Date_of_death TYPE TIMESTAMP WITH TIME ZONE USING Date_of_death AT TIME ZONE 'UTC';

ALTER TABLE Sins_Reports ALTER COLUMN Uploaded_At TYPE TIMESTAMP WITH TIME ZONE USING Uploaded_At AT TIME ZONE 'UTC';
ALTER TABLE Goodness_Reports ALTER COLUMN Uploaded_At TYPE TIMESTAMP WITH TIME ZONE USING Uploaded_At AT TIME ZONE 'UTC';

ALTER TABLE Sin_Evidences ALTER COLUMN Date_Of_Sin TYPE TIMESTAMP WITH TIME ZONE USING Date_Of_Sin AT TIME ZONE 'UTC';
ALTER TABLE Sin_Evidences ALTER COLUMN Attoned_At TYPE TIMESTAMP WITH TIME ZONE USING Attoned_At AT TIME ZONE 'UTC';
ALTER TABLE Goodness_Evidences ALTER COLUMN Date_Of_Good_Deed_Evidence TYPE TIMESTAMP WITH TIME ZONE USING Date_Of_Good_Deed_Evidence AT TIME ZONE 'UTC';
